import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar placeholder */}
        <nav className="w-full flex items-center justify-between py-4 px-6 border-b border-gray-200 dark:border-gray-800">
          <div className="font-bold text-lg">Makaila Schneider</div>
          <div className="space-x-4">
            <a href="#about" className="hover:underline">About</a>
            <a href="#stats" className="hover:underline">Stats</a>
            <a href="#videos" className="hover:underline">Videos</a>
            <a href="#gallery" className="hover:underline">Gallery</a>
            <a href="#contact" className="hover:underline">Contact</a>
          </div>
        </nav>
        <main className="min-h-screen flex flex-col items-center justify-center">
          {children}
        </main>
        {/* Footer placeholder */}
        <footer className="w-full py-6 flex flex-col items-center border-t border-gray-200 dark:border-gray-800 mt-8">
          <div className="flex space-x-4 mb-2">
            <a href="https://twitter.com/SoftballMakaila" target="_blank" rel="noopener noreferrer" className="hover:underline">Twitter</a>
            <a href="https://instagram.com/makailasoftball24" target="_blank" rel="noopener noreferrer" className="hover:underline">Instagram</a>
            <a href="#" className="hover:underline">SportsRecruits</a>
          </div>
          <div className="text-xs text-gray-500">&copy; {new Date().getFullYear()} Makaila Schneider. All rights reserved.</div>
        </footer>
      </body>
    </html>
  );
}
